### ISSUE TITLE
Rechtsklassifikation : leerer Index

### ISSUE THREAD

**Issue by oschihin** [swissbib/content2SearchDocs#36]
## Problem

Der Index der Rechtsklassifikation (Klasse F : Europäische Integration) ist leer. Eine solr-Suche mit 'classif_drsys_F:*' ergibt null Treffer.
## Analyse
- Entsprechend das Template im Step2 anschauen
- Woran liegt das? Ist das ev. sogar gewollt?

@ToVie : any idea?

**Comment by ToVie** [comment]
@oschihin das ist so gewollt: F-Werte werden soweit mögl. auf A/B/C-Werte gemappt oder sonst ins Nirvana geschickt. Der F-Index ist ein Relikt aus früheren Entwicklungsstufen...

**Comment by oschihin** [comment]
@ToVie : Alles klar, danke.

**Comment by guenterh** [comment]
closed - s. Antwort von Tobias
