### ISSUE TITLE
index exception while archiving raw data 

### ISSUE THREAD

**Issue by guenterh** [swissbib/content2SearchDocs#42]
Traceback (most recent call last):
  File "/usr/local/swissbib/bin/copyDumpedMongoCollections.py", line 35, in <module>
    tag = wochentag[datetime.today().weekday() + 1]
IndexError: list index out of range

look into crontab / happens only on Sunday

(sb-udb5 / sb-udb6 / sb-udb7)

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[content2SearchDocs] index exception while archiving raw data](https://trello.com/c/fhFnCDho/344-content2searchdocs-index-exception-while-archiving-raw-data)

**Comment by liowalter** [comment]
@guenterh : could you check my fix and deploy it if it is ok ?
